Repository 2023WB-TeamB/Frontend, pull requests merged in 2024-01, with the labels that each got.

#2 [chore/#1] 개발 환경 세팅
  .eslintrc.cjs
  .gitignore
  .prettierrc
  README.md
  index.html
  package.json
  public/gtd.svg
  src/App.css
  src/App.tsx
  src/components/Header.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/index.css
  src/main.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocPage.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: 환경설정

#11 [chore] docker 세팅
  Dockerfile
  docker-compose.dev.yml
  package.json
  vite.config.ts
Labels: 환경설정

#10 [design/#9] Register Modal 퍼블리싱
  src/assets/images/deco_bar.png
  src/components/Register.tsx
  src/pages/MainPage.tsx
  tsconfig.json
Labels: 퍼블리싱

#24 [Design/#16] 뷰어/에디터 주요 퍼블리싱 완료
  package.json
  src/assets/images/arrow_left.png
  src/assets/images/arrow_right.png
  src/assets/images/cancel.png
  src/assets/images/closeIcon.png
  src/assets/images/confirm.png
  src/assets/images/delete button.png
  src/assets/images/edit.png
  src/assets/images/exit button.png
  src/assets/images/gallery button.png
  src/assets/images/pdf.png
  src/assets/images/profile.png
  src/assets/images/qr-code-add.png
  src/assets/images/save.png
  src/assets/images/search.png
  src/assets/images/share button.png
  src/assets/images/upload-cloud.png
  src/assets/images/url.png
  src/assets/images/version button.png
  src/components/BackDrop.tsx
  src/components/ConfirmButton.tsx
  src/components/MarkdownArea.tsx
  src/components/ModalConfirm.tsx
  src/components/ModalOptions.tsx
  src/components/OptionButton.tsx
  src/components/Sidebar/Preview.tsx
  src/components/Sidebar/PreviewTile.tsx
  src/components/Sidebar/SidebarList.tsx
  src/components/Sidebar/SidebarPanel.tsx
  src/components/Sidebar/TileButton.tsx
  src/pages/ViewerPage.tsx
  yarn.lock
Labels: 퍼블리싱

#25 [Design/#13] Signin Modal 퍼블리싱
  package.json
  src/components/Header.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#31 [design/#22] 마이독스(하단) 페이지 퍼블리싱
  src/assets/images/mydocs/arrow.svg
  src/assets/images/mydocs/document.svg
  src/assets/images/mydocs/github.svg
  src/components/mydocs/Card.tsx
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/data.json
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/Description.tsx
  src/components/mydocs/upper/Documentation.tsx
  src/components/mydocs/upper/GiToDoc.tsx
  src/components/mydocs/upper/LanguageToggle.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
Labels: 퍼블리싱

#33 [Feat/#29] Signin API 연동
  src/components/Signin.tsx
Labels: 기능구현

#32 [feat/#20] Register API 연동 구현
  package.json
  src/components/Register.tsx
  yarn.lock
Labels: 기능구현

#37 [Refactor/#36] 뷰어/에디터 디렉토리 구조 변경
  src/components/ViewEdit/BackDrop.tsx
  src/components/ViewEdit/ConfirmButton.tsx
  src/components/ViewEdit/MarkdownArea.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/OptionButton.tsx
  src/components/ViewEdit/Sidebar/Preview.tsx
  src/components/ViewEdit/Sidebar/PreviewTile.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
Labels: 리팩토링

#43 [feat/#28] 문서 생성 API 연동
  src/components/mydocs/upper/LanguageToggle.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/store/store.ts
Labels: 기능구현

#41 [Feat/#34] 로그아웃 API 연동 및 JWT인증 기능 구현
  src/components/Header.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/pages/MyDocsPage.tsx
Labels: 기능구현

#45 [Feat/#30] 문서 공유 API 연동 및 URL 복사, QR 생성 기능 구현
  package.json
  src/components/ViewEdit/BackDrop.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/pages/ViewerPage.tsx
  yarn.lock
Labels: 기능구현

#48 [design/#40] 메인페이지 스크롤 및 애니메이션 구현
  package.json
  src/GlobalStyle.tsx
  src/assets/images/MainPage/GitPage.svg
  src/assets/images/MainPage/bar.svg
  src/assets/images/MainPage/document.svg
  src/assets/images/MainPage/document1.svg
  src/assets/images/MainPage/down_arrow.svg
  src/assets/images/MainPage/file.svg
  src/assets/images/MainPage/folder.svg
  src/assets/images/MainPage/githublogo.svg
  src/assets/images/MainPage/logobox.svg
  src/assets/images/MainPage/logoboxopen.svg
  src/assets/images/MainPage/pointer.svg
  src/assets/images/MainPage/step2page.svg
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/pages/MainPage.tsx
  yarn.lock
Labels: 퍼블리싱

#47 [feat/#44] 문서 조회 API 연동
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/store/types.ts
Labels: 기능구현

#52 [Design/#46] 모달 애니메이션 추가 및 컴포넌트 모듈화
  src/components/CloseBtn.tsx
  src/components/GradientBtn.tsx
  src/components/Header.tsx
  src/components/MainPage/page5.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/pages/MainPage.tsx
Labels: 리팩토링, 퍼블리싱

#55 [Refactor/#53] 모달 상태관리
  src/components/Header.tsx
  src/components/MainPage/page5.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/components/useModalStore.tsx
  src/pages/MainPage.tsx
Labels: 리팩토링

#57 [design/#51] 마이독스 페이지 UI 수정
  package.json
  src/assets/images/mydocs/btn.svg
  src/assets/images/mydocs/viewDetails.svg
  src/components/mydocs/Card.tsx
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/ViewDetailsButton.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/Description.tsx
  src/components/mydocs/upper/Documentation.tsx
  src/components/mydocs/upper/GiToDoc.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  yarn.lock
Labels: 퍼블리싱

#61 [design/#60] 프론트엔드 에러 수정
  Dockerfile
  src/components/Header.tsx
  src/components/MainPage/page3.tsx
  src/components/Signin.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#67 [Design/#26] 에디터 디자인, 기능 업데이트
  Dockerfile
  package.json
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/EditorComps/TiptapStyles.css
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/MarkdownArea.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/pages/ViewerPage.tsx
  yarn.lock
Labels: 기능구현, 리팩토링, 퍼블리싱

#70 [Refactor/#69]: 사이드바 관련 상태 관리 적용
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 리팩토링

#72 [feat/#58] 팔레트 기능 추가
  package.json
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/data.json
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/main.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
  src/store/types.ts
  yarn.lock
Labels: 기능구현

#74 [feat/#73] 문서 삭제 기능 구현
  src/components/mydocs/ModalContent.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
Labels: 기능구현

#66 [feat/#65] 문서 생성 기본 색상 추가
  src/components/mydocs/upper/URLInput.tsx
  src/components/mydocs/upper/defaultColors.json
Labels: 기능구현

#76 [design/#62] 메인페이지 반응형 구현 및 애니메이션 수정
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/pages/MainPage.tsx
Labels: 기능구현, 퍼블리싱

#77 [feat/#75] 문서 생성 로딩 애니메이션 추가
  src/assets/images/MainPage/document2.svg
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/Loading.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
  src/store/types.ts
Labels: 기능구현, 퍼블리싱

#83 [Design/#71] 뷰어/에디터 디자인, 기능 보완 1차
  package.json
  src/assets/images/Viewer/arrow_left.png
  src/assets/images/Viewer/arrow_left_dark.svg
  src/assets/images/Viewer/arrow_right.png
  src/assets/images/Viewer/arrow_right_dark.svg
  src/assets/images/Viewer/cancel.png
  src/assets/images/Viewer/cancel_dark.svg
  src/assets/images/Viewer/closeIcon.png
  src/assets/images/Viewer/closeIcon_dark.svg
  src/assets/images/Viewer/confirm.png
  src/assets/images/Viewer/confirm_dark.svg
  src/assets/images/Viewer/delete button.png
  src/assets/images/Viewer/deletebutton_dark.svg
  src/assets/images/Viewer/double-arrow-left.png
  src/assets/images/Viewer/double-arrow-right.png
  src/assets/images/Viewer/edit.png
  src/assets/images/Viewer/edit_dark.svg
  src/assets/images/Viewer/exit button.png
  src/assets/images/Viewer/gallery button.png
  src/assets/images/Viewer/gallerybutton_dark.svg
  src/assets/images/Viewer/pdf.png
  src/assets/images/Viewer/pdf_dark.svg
  src/assets/images/Viewer/profile.png
  src/assets/images/Viewer/qr-code-add.png
  src/assets/images/Viewer/qr-code-add_dark.svg
  src/assets/images/Viewer/save.png
  src/assets/images/Viewer/share button.png
  src/assets/images/Viewer/sharebutton_dark.svg
  src/assets/images/Viewer/upload-cloud.png
  src/assets/images/Viewer/upload-cloud_dark.svg
  src/assets/images/Viewer/url.png
  src/assets/images/Viewer/url_dark.svg
  src/assets/images/Viewer/version button.png
  src/assets/images/Viewer/versionbutton_dark.svg
  src/assets/images/search.png
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/TiptapStyles.css
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/GalleryPreviewTile.tsx
  src/components/ViewEdit/Sidebar/Preview.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewTile.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
  yarn.lock
Labels: 기능구현, 리팩토링, 퍼블리싱

#86 [design/#81] 메인페이지 피드백 반영 디자인 수정
  src/assets/images/MainPage/down_arrow.svg
  src/assets/images/MainPage/page2.svg
  src/assets/images/MainPage/page2_dark.svg
  src/assets/images/MainPage/settings.svg
  src/assets/images/MainPage/settings_dark.svg
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/components/ViewEdit/DocField.tsx
  src/pages/MainPage.tsx
  vite.config.ts
Labels: 퍼블리싱

#90 [Design/#84] 사이드바 고정 상태 전용 디자인 반영
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/OptionButton.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/GalleryPreviewArea.tsx
  src/components/ViewEdit/Sidebar/GalleryPreviewTile.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 리팩토링, 퍼블리싱

#92 [refactor/#78] 검색 상태관리 적용 및 검색 필터 기능 구현
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/useDebounce.tsx
  src/components/useModalStore.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링

#97 [design/#95] 로그인, 로그아웃 알림 디자인 수정
  src/components/Header.tsx
  src/components/Signin.tsx
  src/pages/MainPage.tsx
Labels: 기능구현, 퍼블리싱

#98 [design/#89] 모달/프리뷰 피그마 디자인 적용
  package.json
  src/assets/images/mydocs/viewDetails.svg
  src/components/Signin.tsx
  src/components/mydocs/Card.tsx
  src/components/mydocs/DeleteButton.tsx
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/PalleteButton.tsx
  src/components/mydocs/ViewDetailsButton.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/Preview.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/lower/getContent.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
  yarn.lock
Labels: 퍼블리싱

#99 [design/#88] Register, Sign-in 디자인 고도화
  src/components/GradientBtn.tsx
  src/components/Register.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/Signin.tsx
Labels: 퍼블리싱

#104 [design/#102] Viewer Page 뱃지 가이드 구현
  src/assets/images/Viewer/Badge/help.svg
  src/assets/images/Viewer/Badge/helpPage.svg
  src/assets/images/Viewer/Badge/helpPage_dark.svg
  src/assets/images/Viewer/Badge/help_dark.svg
  src/assets/images/Viewer/Badge/themes.svg
  src/components/BadgeGuide.tsx
  src/components/useOutsideClick.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 퍼블리싱

#107 [Feat/#96] 뷰어/에디터 컴포넌트 통합 & 렌더링 문제 해결
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
  yarn.lock
Labels: 리팩토링, 오류 수정

#108 [design/#105] 다크모드 구현 및 수정
  src/components/Header.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
Labels: 퍼블리싱

#109 [design/#56] 웹 반응형 디자인
  package.json
  src/components/Header.tsx
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/components/Register.tsx
  src/components/SearchItem.tsx
  src/components/Signin.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/getContent.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
  tsconfig.json
  yarn.lock
Labels: 퍼블리싱

#115 [design/#111] 피드백 반영 디자인 수정
  src/components/CloseBtn.tsx
  src/components/Header.tsx
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page5.tsx
  src/components/Register.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/Signin.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/Loading.tsx
  src/index.css
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
Labels: 기능구현, 리팩토링, 퍼블리싱

#112 [Feat/#94] 뷰어 패널 검색 기능 구현
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/store/store.ts
Labels: 기능구현

#116 [design/#114] 마이독스 스켈레톤 UI 적용
  src/components/Header.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/GallerySkeleton.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/upper/CarouselSkeleton.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
Labels: 퍼블리싱

#120 [refactor/#118] 마이독스 로직 개선 1/2
  .eslintrc.cjs
  src/components/mydocs/Card.tsx
  src/components/mydocs/DeleteButton.tsx
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/PalleteButton.tsx
  src/components/mydocs/ViewDetailsButton.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/GallerySkeleton.tsx
  src/components/mydocs/lower/Preview.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/lower/getContent.tsx
  src/components/mydocs/upper/CarouselSkeleton.tsx
  src/components/mydocs/upper/Description.tsx
  src/components/mydocs/upper/LanguageToggle.tsx
  src/components/mydocs/upper/Loading.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
Labels: 리팩토링

#119 [design/#110] editor 디자인 수정
  src/assets/images/Viewer/bold.svg
  src/assets/images/Viewer/bold_dark.svg
  src/assets/images/Viewer/cancel.svg
  src/assets/images/Viewer/check_box.svg
  src/assets/images/Viewer/check_box_dark.svg
  src/assets/images/Viewer/closeIcon.svg
  src/assets/images/Viewer/code.svg
  src/assets/images/Viewer/code_dark.svg
  src/assets/images/Viewer/color.svg
  src/assets/images/Viewer/color_dark.svg
  src/assets/images/Viewer/confirm.svg
  src/assets/images/Viewer/confirm_dark.svg
  src/assets/images/Viewer/edit.svg
  src/assets/images/Viewer/italic.svg
  src/assets/images/Viewer/italic_dark.svg
  src/assets/images/Viewer/line.svg
  src/assets/images/Viewer/line_dark.svg
  src/assets/images/Viewer/link.svg
  src/assets/images/Viewer/link_dark.svg
  src/assets/images/Viewer/photo_library.svg
  src/assets/images/Viewer/photo_library_dark.svg
  src/assets/images/Viewer/redo.svg
  src/assets/images/Viewer/redo_dark.svg
  src/assets/images/Viewer/save.svg
  src/assets/images/Viewer/strikethrough.svg
  src/assets/images/Viewer/strikethrough_dark.svg
  src/assets/images/Viewer/table.svg
  src/assets/images/Viewer/table_dark.svg
  src/assets/images/Viewer/underlined.svg
  src/assets/images/Viewer/underlined_dark.svg
  src/assets/images/Viewer/undo.svg
  src/assets/images/Viewer/undo_dark.svg
  src/components/ViewEdit/BackDrop.tsx
  src/components/ViewEdit/ConfirmButton.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/OptionButton.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/index.css
  src/pages/ViewerPage.tsx
Labels: 퍼블리싱

#121 [Refactor/#113] 데모용
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/index.css
  src/store/store.ts
Labels: 리팩토링, 퍼블리싱, 오류 수정

#124 [design/#122] 뷰어페이지 디자인 고도화
  src/assets/images/Viewer/double_arrow_left.svg
  src/assets/images/Viewer/double_arrow_left_dark.svg
  src/assets/images/Viewer/double_arrow_right.svg
  src/assets/images/Viewer/double_arrow_right_dark.svg
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/pages/ViewerPage.tsx
Labels: 퍼블리싱

#123 [design/#117] 검색창 디자인 수정 및 코드 리팩토링
  package.json
  src/components/CloseBtn.tsx
  src/components/GradientBtn.tsx
  src/components/Header.tsx
  src/components/Register.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/Signin.tsx
  src/components/useDebounce.tsx
  src/components/useModalStore.tsx
  yarn.lock
Labels: 기능구현, 리팩토링, 퍼블리싱

#126 [refactor/#118] 마이독스 로직 개선 2/2
  src/assets/images/mydocs/btn.svg
  src/assets/images/mydocs/button_gallery.svg
  src/components/mydocs/Card.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/PalleteButton.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/GallerySkeleton.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/upper/CarouselSkeleton.tsx
  src/components/mydocs/upper/Loading.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/store/store.ts
Labels: 리팩토링

#127 [Refactor/#113] 뷰어 피드백반영
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/GalleryPreviewArea.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/index.css
  src/pages/ViewerPage.tsx
Labels: 리팩토링

#131 [Refactor/#113] 뷰어 eslint 적용 및 갤러리 디자인 수정
  src/components/ViewEdit/ConfirmButton.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/OptionButton.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/pages/ViewerPage.tsx
Labels: 리팩토링, 퍼블리싱

#133 [design/#129] 디자인 수정 피드백 반영
  src/assets/images/LOGO1.png
  src/assets/images/dark_mode.png
  src/assets/images/dark_mode.svg
  src/assets/images/deco_bar.png
  src/assets/images/moon.svg
  src/assets/images/search.png
  src/assets/images/signin.png
  src/assets/images/signin_dark.png
  src/assets/images/sun.svg
  src/assets/images/white_mode.png
  src/assets/images/white_mode.svg
  src/components/Header.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
Labels: 리팩토링, 퍼블리싱

#128 [refactor/#125] 메인페이지 eslint 문법 오류 수정
  src/assets/images/MainPage/down_arrow.svg
  src/components/GradientBtn.tsx
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/Description.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/pages/MainPage.tsx
Labels: 리팩토링, 퍼블리싱

#135 [Design/#132] 패널 디자인, 뷰어 태그 디자인 수정
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/store/store.ts
Labels: 퍼블리싱

#136 [design/#134] 마이독스 디자인 수정
  src/assets/images/mydocs/button_gallery.svg
  src/components/ViewEdit/DocField.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/upper/RoundCarousel.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
Labels: 퍼블리싱

#140 [Refactor/#137] 이미지 드래그앤드 기능
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/TiptapStyles.css
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
Labels: 기능구현, 리팩토링, 퍼블리싱

#143 [design/#139] 메인페이지 리팩토링
  src/components/BadgeGuide.tsx
  src/components/Header.tsx
  src/components/MainPage/doubleDownArrow.tsx
  src/components/MainPage/page1.tsx
  src/components/MainPage/page2.tsx
  src/components/MainPage/page3.tsx
  src/components/MainPage/page4.tsx
  src/components/MainPage/page5.tsx
  src/components/MainPage/styledStep.tsx
  src/components/Register.tsx
  src/components/SearchItem.tsx
  src/components/SearchList.tsx
  src/components/Signin.tsx
  src/components/ViewEdit/BackDrop.tsx
  src/components/ViewEdit/ConfirmButton.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BottomMenubar.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/LittleHeader.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/OptionButton.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/components/mydocs/Modal.tsx
  src/components/mydocs/ModalContent.tsx
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/lower/Preview.tsx
  src/components/mydocs/lower/PreviewContent.tsx
  src/components/mydocs/upper/Description.tsx
  src/components/mydocs/upper/Loading.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 리팩토링, 오류 수정

#145 [Refactor/#137] 뷰어 기능 수정 및 디자인 수정 2차
  src/assets/images/Viewer/SmallLeftArrowIcon.png
  src/assets/images/Viewer/SmallRightArrowIcon.png
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/BubbleMenubar.tsx
  src/components/ViewEdit/EditorComps/EditorStyles.css
  src/components/ViewEdit/EditorComps/FixedMenubar.tsx
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/GalleryPreview.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/components/ViewEdit/Sidebar/VersionPreview.tsx
  src/components/ViewEdit/Sidebar/VersionPreviewArea.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 퍼블리싱

#149 [design/#144] 로그아웃 alert 디자인 수정
  src/components/Header.tsx
  src/components/MainPage/page1.tsx
  src/components/MainPage/page5.tsx
  src/components/ModalStore.tsx
  src/components/Register.tsx
  src/components/SearchList.tsx
  src/components/Signin.tsx
  src/components/mydocs/ViewDetailsButton.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
Labels: 퍼블리싱, 오류 수정

#150 [feat/#141] s3 + cloudfront + lambdaEdge 연동
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
Labels: 기능구현

#151 [Refactor/#147] 뷰어 기능 수정 및 디자인 수정 3차
  package.json
  src/App.tsx
  src/components/Header.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/DocTags.tsx
  src/components/ViewEdit/EditorComps/FixedMenubar.tsx
  src/components/ViewEdit/ModalConfirm.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/SidebarList.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/ViewEdit/Sidebar/TileButton.tsx
  src/pages/MainPage.tsx
  src/pages/MyDocsPage.tsx
  src/pages/ViewerPage.tsx
  yarn.lock
Labels: 기능구현, 리팩토링, 퍼블리싱

#155 [Feat/#146] 뷰어 최종 기능 추가
  src/assets/images/Viewer/edit.png
  src/components/Header.tsx
  src/components/Register.tsx
  src/components/Signin.tsx
  src/components/ViewEdit/DocField.tsx
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/ExternalArea.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/components/ViewEdit/Sidebar/SidebarPanel.tsx
  src/components/mydocs/PalleteButton.tsx
  src/components/mydocs/lower/getContent.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 기능구현, 리팩토링, 퍼블리싱
