Repository 2023WB-TeamB/Frontend, pull requests merged in 2024-02, with the labels that each got.

#157 [design/#156] logo 수정
  src/components/Header.tsx
Labels: 퍼블리싱

#159 [Refactor/#158] 조기 PR
  package.json
  src/components/BadgeGuide.tsx
  src/components/ViewEdit/EditorComps/EditorStyles.css
  src/components/ViewEdit/EditorComps/WYSIWYG_Area.tsx
  src/components/ViewEdit/ModalOptions.tsx
  src/store/store.ts
Labels: 리팩토링, 오류 수정

#161 [refactor/#160] 문서 생성 알림, 마이독스 반응형 수정
  src/components/mydocs/lower/Gallery.tsx
  src/components/mydocs/upper/URLInput.tsx
  src/pages/MyDocsPage.tsx
  src/pages/ViewerPage.tsx
  src/store/store.ts
Labels: 리팩토링

#163 [Design/#162] mydocs 문서 삭제 alert 수정
  src/components/mydocs/DeleteButton.tsx
  src/pages/MyDocsPage.tsx
Labels: 리팩토링, 퍼블리싱
